######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 23 14:57:56 2019
######################################################################

TEMPLATE = app
TARGET = histogram
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += histogram.h qcustomplot.h
SOURCES += histogram.cpp main.cpp qcustomplot.cpp
TARGET=histogram
CONFIG+=Debug
OBJECTS_DIR = build/obj
MOC_DIR = build/moc
QT += gui core svg
