######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 15 09:36:32 2019
######################################################################

TEMPLATE = app
TARGET = svgui
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += svgui.h
SOURCES += main.cpp svgui.cpp
TARGET=svgui
CONFIG+=Debug
OBJECTS_DIR = build/obj
MOC_DIR = build/moc
QT += gui core svg
